### ISSUE TITLE
Identify all the submodules

### ISSUE THREAD

**Issue by cristirusu** [crowdfavorite/wp-capsule-ui#21]
Identify all the submodules and the functionality used from submodules.
Check:
- if the submodules are at the latest version - OK
- if there is a develop branch with updated code (CF submodule) - if code is old try to update the master from develop and update to current coding standards
- if the submodules are unmaintained forks of external repos - update the project to use the external repo

In the end the submodules will be removed, code from submodules will be included in main project repo or will be included via Composer.

**Comment by al-esc** [comment]
Closing as it's tracked in #48
