### ISSUE TITLE
Add title attributes to sidebar navigation

### ISSUE THREAD

**Issue by JeremyDunn** [crowdfavorite/wp-capsule-ui#41]
It's not obvious what some of the icons in the sidebar are for until you click them. Adding title attributes to the anchor tags will allow the user to see tooltips when the hover their mouse over the icons.

cc @cristirusu

**Comment by al-esc** [comment]
addressed in #49

**Comment by al-esc** [comment]
added in [v1.3.0](https://github.com/crowdfavorite/wp-capsule-ui/releases/tag/v1.3.0)
