### ISSUE TITLE
Add external link icon to server list

### ISSUE THREAD

**Issue by JeremyDunn** [crowdfavorite/wp-capsule-ui#42]
The list of capsule servers just displays links to the servers home page. Adding an external link icon before the server name would make it clear that you're just opening a link to the server URL itself.

cc @cristirusu

**Comment by al-esc** [comment]
addressed in #49

**Comment by al-esc** [comment]
added in [v1.3.0](https://github.com/crowdfavorite/wp-capsule-ui/releases/tag/v1.3.0)
